#Requires -Version 7.0
<#
.SYNOPSIS
    Genere docs/COVERAGE.md et docs/COVERAGE.en.md : mode de verification de chaque exigence.

.DESCRIPTION
    Le tableau est derive du catalogue lui-meme (champs Mode, Phase, AuthMode,
    RequiresLicense, Scored du schema 1.1). Aucune table codee en dur : ajouter une
    exigence au referentiel suffit a la voir apparaitre ici.

.EXAMPLE
    .\tools\New-CceCoverageDoc.ps1
#>
[CmdletBinding()]
param(
    [string] $Root = (Split-Path -Parent $PSScriptRoot)
)

Set-StrictMode -Version Latest
$ErrorActionPreference = 'Stop'

# Regroupement des modes techniques en trois familles lisibles par un lecteur non technique.
$famille = @{
    'graph'         = 'Auto'
    'graph-beta'    = 'Auto'
    'exchange'      = 'Auto'
    'sharepoint'    = 'Auto'
    'teams'         = 'Auto'
    'purview'       = 'Auto'
    'powerplatform' = 'Auto'
    'mscommerce'    = 'Auto'
    'workstation'   = 'Local'
    'manual'        = 'Manual'
}

$labels = @{
    fr = @{
        Title      = '# Couverture des controles'
        Intro      = 'Genere par `tools/New-CceCoverageDoc.ps1` depuis le referentiel. Base : {0} v{1} ({2} exigences).'
        ModeHeader = '| Mode | Nombre | Signification |'
        Auto       = 'Automatique'
        Local      = 'Poste local'
        Manual     = 'Manuel'
        AutoDesc   = "Statut deduit d'une interrogation du tenant."
        LocalDesc  = 'Necessite `-IncludeLocalChecks` sur un poste de reference.'
        ManualDesc = 'Aucune API publique : le moteur documente la procedure et laisse le statut a valider.'
        TableHead  = '| # | Exigence | Priorite | Phase | Mode | Source interrogee | Notee |'
        TableSep   = '| ---: | --- | --- | --- | --- | --- | :---: |'
        PhaseMap   = @{ 'pre-deployment' = 'Avant'; 'post-deployment' = 'Apres'; 'both' = 'Avant et apres' }
        Scored     = @{ $true = 'oui'; $false = 'non' }
        LicNote    = '**Licence requise :** {0}'
        Sections   = '## Repartition'
        PhaseTitle = '### Par phase'
        Note       = @'
> Une exigence marquee « non notee » figure au rapport mais ne pese pas sur le taux de
> conformite : capacite en preversion, exigence depreciee, ou volet informatif.
'@
    }
    en = @{
        Title      = '# Check coverage'
        Intro      = 'Generated by `tools/New-CceCoverageDoc.ps1` from the baseline. Source: {0} v{1} ({2} requirements).'
        ModeHeader = '| Mode | Count | Meaning |'
        Auto       = 'Automatic'
        Local      = 'Workstation'
        Manual     = 'Manual'
        AutoDesc   = 'Status derived from a tenant query.'
        LocalDesc  = 'Requires `-IncludeLocalChecks` on a reference workstation.'
        ManualDesc = 'No public API: the engine documents the procedure and leaves the status to be validated.'
        TableHead  = '| # | Requirement | Priority | Phase | Mode | Source queried | Scored |'
        TableSep   = '| ---: | --- | --- | --- | --- | --- | :---: |'
        PhaseMap   = @{ 'pre-deployment' = 'Pre'; 'post-deployment' = 'Post'; 'both' = 'Pre and post' }
        Scored     = @{ $true = 'yes'; $false = 'no' }
        LicNote    = '**Licence required:** {0}'
        Sections   = '## Breakdown'
        PhaseTitle = '### By phase'
        Note       = @'
> A requirement marked "not scored" appears in the report but does not affect the
> compliance rate: preview capability, deprecated requirement, or informational item.
'@
    }
}

$targets = @(
    @{ Lang = 'fr'; Catalog = 'data\checklist-catalog.json';    Output = 'docs\COVERAGE.md' }
    @{ Lang = 'en'; Catalog = 'data\checklist-catalog.en.json'; Output = 'docs\COVERAGE.en.md' }
)

function Get-Field {
    param($Item, [string] $Name, $Default = '')
    $p = $Item.PSObject.Properties[$Name]
    if ($p -and $null -ne $p.Value -and "$($p.Value)" -ne '') { return $p.Value }
    $Default
}

foreach ($target in $targets) {
    $catalogPath = Join-Path $Root $target.Catalog
    if (-not (Test-Path $catalogPath)) { Write-Warning "Catalogue absent : $catalogPath"; continue }

    $catalog = Get-Content -Path $catalogPath -Raw -Encoding utf8 | ConvertFrom-Json
    $L = $labels[$target.Lang]

    $counts = @{ Auto = 0; Local = 0; Manual = 0 }
    foreach ($item in $catalog.items) {
        $mode = "$(Get-Field -Item $item -Name 'Mode' -Default 'manual')"
        $key = if ($famille.ContainsKey($mode)) { $famille[$mode] } else { 'Manual' }
        $counts[$key]++
    }

    $sb = [System.Text.StringBuilder]::new()
    [void]$sb.AppendLine($L.Title)
    [void]$sb.AppendLine()
    [void]$sb.AppendLine(($L.Intro -f $catalog.title, $catalog.version, @($catalog.items).Count))
    [void]$sb.AppendLine()
    [void]$sb.AppendLine($L.ModeHeader)
    [void]$sb.AppendLine('| --- | ---: | --- |')
    [void]$sb.AppendLine("| $($L.Auto) | $($counts.Auto) | $($L.AutoDesc) |")
    [void]$sb.AppendLine("| $($L.Local) | $($counts.Local) | $($L.LocalDesc) |")
    [void]$sb.AppendLine("| $($L.Manual) | $($counts.Manual) | $($L.ManualDesc) |")
    [void]$sb.AppendLine()

    # Repartition par phase : c'est ce qui distingue un audit avant go-live d'un audit d'exploitation.
    [void]$sb.AppendLine($L.PhaseTitle)
    [void]$sb.AppendLine()
    [void]$sb.AppendLine('| Phase | Total |')
    [void]$sb.AppendLine('| --- | ---: |')
    foreach ($phase in 'pre-deployment', 'post-deployment', 'both') {
        $n = @($catalog.items | Where-Object { "$(Get-Field -Item $_ -Name 'Phase' -Default 'pre-deployment')" -eq $phase }).Count
        [void]$sb.AppendLine("| $($L.PhaseMap[$phase]) | $n |")
    }
    [void]$sb.AppendLine()
    [void]$sb.AppendLine($L.Note)
    [void]$sb.AppendLine()

    foreach ($group in ($catalog.items | Group-Object Section)) {
        [void]$sb.AppendLine("## $($group.Name)")
        [void]$sb.AppendLine()
        [void]$sb.AppendLine($L.TableHead)
        [void]$sb.AppendLine($L.TableSep)

        foreach ($item in ($group.Group | Sort-Object { [int] $_.Id })) {
            $mode = "$(Get-Field -Item $item -Name 'Mode' -Default 'manual')"
            $famKey = if ($famille.ContainsKey($mode)) { $famille[$mode] } else { 'Manual' }
            $phase = "$(Get-Field -Item $item -Name 'Phase' -Default 'pre-deployment')"
            $scored = [bool] (Get-Field -Item $item -Name 'Scored' -Default $true)
            $lic = "$(Get-Field -Item $item -Name 'RequiresLicense')"

            $source = "``$mode``"
            if ($lic) { $source += " - $lic" }

            $req = ($item.Requirement -replace '\|', '\|')
            [void]$sb.AppendLine("| $($item.Id) | $req | $($item.Priority) | $($L.PhaseMap[$phase]) | $($L[$famKey]) | $source | $($L.Scored[$scored]) |")
        }
        [void]$sb.AppendLine()
    }

    $outputPath = Join-Path $Root $target.Output
    $dir = Split-Path -Parent $outputPath
    if (-not (Test-Path $dir)) { New-Item -ItemType Directory -Path $dir -Force | Out-Null }
    $sb.ToString() | Set-Content -Path $outputPath -Encoding utf8

    Write-Host ("Couverture [{0}] : {1}  ({2} auto, {3} poste, {4} manuel)" -f `
        $target.Lang.ToUpper(), $outputPath, $counts.Auto, $counts.Local, $counts.Manual) -ForegroundColor Green
}
